# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainRecApp2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 497)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.portLbl = QtWidgets.QLabel(self.centralwidget)
        self.portLbl.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro")
        font.setPointSize(10)
        self.portLbl.setFont(font)
        self.portLbl.setObjectName("portLbl")
        self.horizontalLayout.addWidget(self.portLbl)
        self.portDropdown = QtWidgets.QComboBox(self.centralwidget)
        self.portDropdown.setMinimumSize(QtCore.QSize(100, 22))
        self.portDropdown.setMaximumSize(QtCore.QSize(50, 22))
        self.portDropdown.setEditable(True)
        self.portDropdown.setIconSize(QtCore.QSize(16, 16))
        self.portDropdown.setObjectName("portDropdown")
        self.horizontalLayout.addWidget(self.portDropdown, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filenameLbl = QtWidgets.QLabel(self.centralwidget)
        self.filenameLbl.setMaximumSize(QtCore.QSize(120, 22))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro")
        font.setPointSize(10)
        self.filenameLbl.setFont(font)
        self.filenameLbl.setObjectName("filenameLbl")
        self.horizontalLayout_4.addWidget(self.filenameLbl)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.filenameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.filenameLE.setMinimumSize(QtCore.QSize(250, 0))
        self.filenameLE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.filenameLE.setObjectName("filenameLE")
        self.horizontalLayout_4.addWidget(self.filenameLE)
        spacerItem1 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileLbl = QtWidgets.QLabel(self.centralwidget)
        self.fileLbl.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro")
        font.setPointSize(10)
        self.fileLbl.setFont(font)
        self.fileLbl.setObjectName("fileLbl")
        self.horizontalLayout_2.addWidget(self.fileLbl)
        self.filepathTB = QtWidgets.QTextBrowser(self.centralwidget)
        self.filepathTB.setMinimumSize(QtCore.QSize(350, 30))
        self.filepathTB.setMaximumSize(QtCore.QSize(450, 30))
        self.filepathTB.setObjectName("filepathTB")
        self.horizontalLayout_2.addWidget(self.filepathTB)
        self.fileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fileBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro")
        font.setPointSize(10)
        self.fileBtn.setFont(font)
        self.fileBtn.setObjectName("fileBtn")
        self.horizontalLayout_2.addWidget(self.fileBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startRecBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startRecBtn.setMinimumSize(QtCore.QSize(200, 60))
        self.startRecBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro")
        font.setPointSize(12)
        self.startRecBtn.setFont(font)
        self.startRecBtn.setObjectName("startRecBtn")
        self.horizontalLayout_3.addWidget(self.startRecBtn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.portLbl.setText(_translate("MainWindow", "Port"))
        self.filenameLbl.setText(_translate("MainWindow", "Dateiname"))
        self.fileLbl.setText(_translate("MainWindow", "Speicherort"))
        self.fileBtn.setText(_translate("MainWindow", "Durchsuchen"))
        self.startRecBtn.setText(_translate("MainWindow", "Messungen starten"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
